// Starter data. Everything here is editable inside the app.
import crypto from "crypto";

// STARTER CURRICULUM, 5 years (MBChB, as at Lusaka Apex Medical University; the internship after year 5 is not a course year). This is a TYPICAL medical-school layout built from general
// knowledge. It is NOT the official outline of any university. Replace it with your own school's outline
// (Course outline > Import from your handbook), then edit freely.
const T = (title, topics) => ({ title, topics });
export const STARTER_VERSION = 4; // raise this when courses are added below, so existing users get the new ones once
export const STARTER = {
  1: [
    T("Anatomy", ["Upper limb", "Lower limb", "Thorax", "Abdomen and pelvis", "Head and neck", "Neuroanatomy"]),
    T("Physiology", ["Cell and membrane physiology", "Cardiovascular", "Respiratory", "Renal and fluids", "Gastrointestinal", "Endocrine", "Nervous system"]),
    T("Biochemistry", ["Amino acids and proteins", "Enzymes", "Vitamins and coenzymes", "Bioenergetics and the TCA cycle", "Carbohydrate metabolism", "Lipid metabolism", "Amino acid and nitrogen metabolism", "Nucleotide metabolism", "Molecular biology and genetics", "Hormones and signal transduction", "Clinical biochemistry"]),
    T("Histology & Embryology", ["Basic tissues", "Organ system histology", "General embryology", "Systemic embryology"]),
    T("Introduction to Clinical Medicine", ["Communication skills", "Medical ethics", "History taking", "Basic life support"]),
    T("General & Inorganic Chemistry", ["Atomic structure and chemical bonding", "Solutions and concentration", "Acids, bases and buffer systems", "Chemical kinetics and equilibrium", "Redox reactions and electrochemistry", "Biogenic elements and complex compounds", "Colloids and surface phenomena"]),
    T("Organic Chemistry", ["Hydrocarbons and nomenclature", "Isomerism and stereochemistry", "Alcohols, phenols and ethers", "Aldehydes and ketones", "Carboxylic acids and derivatives", "Amines and amino acids", "Heterocyclic compounds", "Carbohydrates", "Lipids", "Reaction mechanisms"]),
    T("Medical Biology & Genetics", ["Cell structure and function", "Cell division and the cell cycle", "Molecular basis of heredity", "Patterns of inheritance", "Chromosomal and genetic disorders", "Population genetics", "Medical parasitology basics", "Evolution and ecology"]),
    T("Medical Physics & Biophysics", ["Mechanics and fluid flow in the body", "Bioelectricity and membrane potentials", "Optics and the eye", "Acoustics and ultrasound", "Radiation physics and dosimetry", "Medical imaging physics", "Thermodynamics of living systems"]),
    T("Latin & Medical Terminology", ["Latin grammar basics", "Anatomical terminology", "Clinical terminology and word roots", "Prescription writing in Latin", "Pharmaceutical terms"]),
    T("Medical Informatics & Biostatistics", ["Data types and descriptive statistics", "Probability and distributions", "Hypothesis testing", "Correlation and regression", "Evidence-based medicine", "Medical information systems"]),
    T("History of Medicine & Bioethics", ["Ancient and medieval medicine", "Modern medicine", "Ethical principles", "Consent and confidentiality", "Research ethics"]),
    T("Neuroscience", ["Neuron and synapse", "Sensory systems", "Motor systems", "Cranial nerves", "Higher functions"]),
    T("English for Medical Purposes", ["Medical vocabulary", "Patient communication in English", "Reading scientific articles", "Writing case reports"]),
  ],
  2: [
    T("Pathology", ["Cell injury and inflammation", "Neoplasia", "Haematology", "Cardiovascular pathology", "Respiratory pathology", "GI and liver pathology", "Renal pathology"]),
    T("Pharmacology", ["General principles", "Autonomic drugs", "Cardiovascular drugs", "Antimicrobials", "CNS drugs", "Endocrine drugs", "Respiratory drugs", "Gastrointestinal drugs", "Drugs affecting blood", "Analgesics, NSAIDs and anaesthetics", "Antimalarial, antiparasitic and antiviral drugs", "Anticancer and immunosuppressant drugs", "Toxicology and antidotes"]),
    T("Microbiology & Parasitology", ["Bacteriology", "Virology", "Mycology", "Parasitology (malaria, helminths)", "Infection control"]),
    T("Immunology", ["Innate and adaptive immunity", "Hypersensitivity", "Autoimmunity", "Immunodeficiency and HIV"]),
    T("Community Health & Epidemiology", ["Epidemiology basics", "Biostatistics", "Primary health care", "Health systems"]),
    T("Pathological Anatomy", ["Methods: autopsy, biopsy and cytology", "Cell injury, necrosis and apoptosis", "Disorders of circulation: thrombosis, embolism, infarction", "Inflammation and repair", "Immunopathology", "Tumours: classification and spread", "Atherosclerosis and heart disease", "Lung and respiratory pathology", "Gastrointestinal and liver pathology", "Kidney and urinary tract pathology", "Endocrine pathology", "Nervous system pathology", "Infectious disease pathology"]),
    T("Pathological Physiology", ["Aetiology and pathogenesis", "Inflammation and fever", "Hypoxia", "Disorders of carbohydrate and lipid metabolism", "Acid-base and water-electrolyte disorders", "Shock and microcirculation", "Heart, lung, liver and kidney failure", "Tumour growth", "Stress and adaptation"]),
    T("Operative Surgery & Topographic Anatomy", ["Surgical instruments and suturing", "Topographic anatomy of the head and neck", "Chest and abdomen", "Limbs and vascular access", "Basic operations", "Surgical approaches"]),
    T("Hygiene & Ecology", ["Environmental health", "Nutrition and food safety", "Occupational health", "Water, air and soil hygiene", "Hospital hygiene", "Preventive medicine"]),
    T("Clinical Immunology & Allergy", ["Allergic disease", "Transplant immunology", "Immunodeficiency work-up", "Vaccines"]),
    T("Basic Radiology & Imaging", ["X-ray principles", "Ultrasound", "CT and MRI basics", "Radiation safety"]),
    T("Propaedeutics of Internal Diseases", ["Patient interview and general examination", "Cardiovascular examination", "Respiratory examination", "Abdominal examination", "ECG basics", "Laboratory and instrumental methods", "Symptoms and syndromes"]),
  ],
  3: [
    T("Internal Medicine", ["Cardiology", "Respiratory medicine", "Gastroenterology", "Nephrology", "Endocrinology", "Infectious diseases", "Haematology"]),
    T("General Surgery", ["Principles of surgery", "Acute abdomen", "Trauma", "Breast and endocrine surgery", "Urology"]),
    T("Clinical Skills", ["Examination of systems", "Procedures", "Interpreting investigations"]),
    T("Behavioural Science", ["Psychology basics", "Sociology and health", "Medical ethics and law"]),
    T("Clinical Pharmacology", ["Drug interactions", "Adverse drug reactions", "Prescribing in special groups", "Therapeutic drug monitoring", "Rational use of antibiotics"]),
    T("Cardiology", ["Ischaemic heart disease", "Heart failure", "Arrhythmias and ECG", "Valvular and congenital heart disease", "Hypertension", "Cardiomyopathy, myocarditis and pericarditis"]),
    T("Pulmonology", ["Asthma and COPD", "Pneumonia", "Pleural disease", "Interstitial lung disease", "Pulmonary embolism and hypertension", "Lung cancer"]),
    T("Gastroenterology & Hepatology", ["Oesophagus and stomach", "Inflammatory bowel disease", "Liver disease and cirrhosis", "Pancreas and biliary disease", "GI bleeding"]),
    T("Nephrology", ["Acute kidney injury", "Chronic kidney disease", "Glomerular disease", "Electrolyte and acid-base disorders", "Dialysis and transplantation"]),
    T("Haematology", ["Anaemias", "Leukaemias and lymphomas", "Bleeding and clotting disorders", "Transfusion medicine", "Sickle cell disease"]),
    T("Rheumatology", ["Rheumatoid arthritis", "SLE and connective tissue disease", "Gout and crystal arthropathy", "Vasculitis", "Spondyloarthropathies"]),
    T("Nutrition & Dietetics", ["Nutrients and energy balance", "Diet in disease", "Malnutrition and obesity", "Enteral and parenteral feeding"]),
  ],
  4: [
    T("Obstetrics & Gynaecology", ["Antenatal care", "Labour and delivery", "Obstetric emergencies", "Gynaecology", "Family planning"]),
    T("Paediatrics", ["Growth and development", "Neonatology", "Childhood infections and immunisation", "Nutrition", "Paediatric emergencies"]),
    T("Psychiatry", ["Mood disorders", "Psychotic disorders", "Anxiety and substance use", "Psychopharmacology"]),
    T("Neurology", ["Stroke", "Epilepsy", "Neuromuscular disease", "Headache"]),
    T("Infectious Diseases", ["Fever and sepsis", "Respiratory and enteric infections", "HIV and sexually transmitted infections", "Viral hepatitis", "Tropical diseases", "Antimicrobial stewardship"]),
    T("Endocrinology", ["Diabetes mellitus", "Thyroid disease", "Adrenal and pituitary disorders", "Metabolic bone disease", "Obesity"]),
    T("Geriatrics", ["Ageing physiology", "Falls and frailty", "Dementia and delirium", "Polypharmacy", "Palliative and end-of-life care"]),
    T("Urology", ["Urinary tract stones", "Prostate disease", "Urinary tract tumours", "Urinary tract infection and obstruction", "Male reproductive disorders"]),
    T("Dermatology & Venereology", ["Eczema and psoriasis", "Skin infections and infestations", "Skin cancers", "Sexually transmitted infections"]),
  ],
  5: [
    T("Emergency Medicine", ["Resuscitation", "Shock", "Poisoning", "Trauma care"]),
    T("Orthopaedics", ["Fractures", "Joint disease", "Paediatric orthopaedics"]),
    T("Ophthalmology & ENT", ["Common eye conditions", "Ear, nose and throat conditions"]),
    T("Family Medicine & Public Health", ["Chronic disease care", "Preventive medicine", "Health programmes"]),
    T("Forensic Medicine", ["Medico-legal practice", "Death and certification"]),
    T("Dermatology & Radiology", ["Common skin diseases", "Imaging basics"]),
    T("Oncology", ["Cancer biology and screening", "Common cancers", "Chemotherapy, radiotherapy and surgery", "Palliative care"]),
    T("Anaesthesiology & Intensive Care", ["Airway management", "Anaesthetic techniques", "Fluid and shock management", "Pain management", "ICU basics"]),
    T("Phthisiology (Tuberculosis)", ["Epidemiology and transmission", "Diagnosis", "Treatment regimens", "Drug-resistant TB", "Prevention"]),
    T("Neurosurgery", ["Head injury", "Raised intracranial pressure", "Spinal cord compression", "Brain tumours", "Hydrocephalus"]),
    T("Paediatric Surgery", ["Congenital anomalies", "Neonatal surgical emergencies", "Hernias and the acute abdomen in children", "Paediatric trauma"]),
    T("Cardiothoracic Surgery", ["Chest trauma", "Coronary and valve surgery", "Lung and pleural surgery", "Thoracic outlet and mediastinum"]),
    T("Palliative Care", ["Pain and symptom control", "Communication and breaking bad news", "End-of-life care", "Care in HIV and cancer"]),
    T("Rehabilitation & Sports Medicine", ["Stroke and spinal rehabilitation", "Musculoskeletal injuries", "Disability assessment"]),
    T("Occupational & Disaster Medicine", ["Occupational diseases", "Mass casualty triage", "Outbreak response"]),
    T("Advanced Internal Medicine", ["Cardiology cases", "Pulmonology cases", "Gastroenterology and hepatology cases", "Nephrology and rheumatology cases", "Differential diagnosis practice"]),
    T("Advanced Surgery", ["Perioperative care", "Surgical emergencies", "Vascular and thoracic surgery", "Surgical oncology", "Post-operative complications"]),
    T("Health Management & Public Health", ["Health policy", "Quality and patient safety", "Clinical audit", "Medical law"]),
    T("ECG & Imaging Interpretation", ["ECG patterns", "Chest X-ray", "Abdominal imaging", "CT and ultrasound basics"]),
    T("Clinical Research Project", ["Research question and design", "Data collection and analysis", "Writing and presenting"]),
    T("State Exam Revision", ["Basic sciences recap", "Clinical sciences recap", "Practical skills (OSCE)", "Mock exams"]),
  ],
};


// ---- MORE TOPICS (added in 1.5): the first lists were short, so every course now has the topics a full course normally covers.
// They are ADDED to the lists above and never replace them. Existing users get them with Course outline > Starter structure > Add.
const MORE = {
  "Anatomy": ["Introduction to anatomy and terminology", "Osteology and arthrology (bones and joints)", "Myology (muscles in general)", "Angiology (blood vessels and lymphatics)", "Peripheral nerves and plexuses", "Heart and great vessels", "Lungs, pleura and mediastinum", "Digestive organs", "Kidneys, ureters and bladder", "Male and female reproductive organs", "Perineum and pelvic floor", "Skull, face and cranial cavity", "Neck: triangles, fascia and organs", "Vertebral column and spinal cord", "Brainstem, cerebellum and cerebrum", "Cranial nerves (anatomy)", "Eye and ear", "Surface and radiological anatomy"],
  "Physiology": ["General physiology and homeostasis", "Blood and body fluids", "Muscle physiology", "Cardiac cycle, ECG and haemodynamics", "Regulation of blood pressure and circulation", "Lung mechanics and gas exchange", "Control of breathing and oxygen transport", "Glomerular filtration and tubular function", "Acid-base balance", "Digestion and absorption", "Liver, bile and the pancreas", "Hypothalamus and pituitary", "Thyroid, adrenal and pancreatic hormones", "Calcium and bone physiology", "Reproductive physiology", "Special senses", "Higher nervous activity, sleep and EEG", "Metabolism and thermoregulation"],
  "Biochemistry": ["Carbohydrate chemistry", "Lipid chemistry and membranes", "Protein structure and folding", "Haem, porphyrins and bilirubin", "Glycogen metabolism", "Gluconeogenesis and the pentose phosphate pathway", "Beta oxidation, ketone bodies and cholesterol", "Urea cycle and amino acid disorders", "Oxidative phosphorylation", "DNA replication, transcription and translation", "Genetic engineering and PCR", "Water, electrolytes and acid-base biochemistry", "Liver, kidney and blood biochemistry", "Biochemistry of connective tissue, muscle and bone", "Inborn errors of metabolism", "Laboratory tests and enzyme diagnostics"],
  "Histology & Embryology": ["Cytology: the cell and its organelles", "Epithelial tissue", "Connective tissue, cartilage and bone", "Blood and haemopoiesis", "Muscle and nervous tissue", "Cardiovascular and lymphoid organs", "Respiratory and digestive system histology", "Urinary and reproductive system histology", "Endocrine glands and skin", "Eye and ear histology", "Gametogenesis and fertilisation", "Implantation, bilaminar and trilaminar disc", "Foetal membranes and placenta", "Development of the heart and vessels", "Development of the face, limbs and gut", "Development of the urogenital and nervous systems", "Congenital malformations"],
  "Introduction to Clinical Medicine": ["Physical examination basics", "Vital signs", "Hand hygiene and infection prevention", "Professionalism and patient safety", "Medical documentation and notes", "First aid and wound care", "The health care system in Zambia", "Teamwork and referral"],
  "General & Inorganic Chemistry": ["Periodic table and properties of elements", "Chemical thermodynamics", "Electrolyte solutions and ionic equilibria", "Hydrolysis of salts", "pH and buffer calculations", "Complex compounds in biology", "Properties of s, p and d block elements", "Laboratory calculations and titration"],
  "Organic Chemistry": ["Alkenes, alkynes and aromatic compounds", "Halogen derivatives", "Thiols, sulphides and sulphur compounds", "Hydroxy and oxo acids", "Amino acids, peptides and proteins", "Nucleic acid bases and nucleotides", "Vitamins and alkaloids", "Polymers and medicinal organic compounds"],
  "Medical Biology & Genetics": ["Gene expression and regulation", "Mutations and DNA repair", "Cytogenetics and karyotypes", "Genetic counselling and prenatal diagnosis", "Immunogenetics and cancer genetics", "Protozoa of medical importance", "Helminths of medical importance", "Arthropods and vectors", "Ontogenesis and ageing", "Human genome and biotechnology"],
  "Medical Physics & Biophysics": ["Biomechanics of bone and muscle", "Haemodynamics and blood flow", "Electrical activity of the heart and ECG physics", "Sound, hearing and audiometry", "Lasers and light in medicine", "X-rays, CT and MRI physics", "Radioactivity and nuclear medicine", "Biophysics of the cell membrane and transport", "Medical devices and electrical safety"],
  "Latin & Medical Terminology": ["Nouns and adjectives: declensions", "Anatomical Latin: bones, muscles, organs", "Greek roots and clinical word parts", "Diagnoses and surgical terms", "Abbreviations in prescriptions", "Names of drugs and chemical substances"],
  "Medical Informatics & Biostatistics": ["Sampling and study design", "Confidence intervals", "Chi-square, t-test and ANOVA", "Non-parametric tests", "Sensitivity, specificity and predictive values", "Survival analysis", "Databases, electronic records and telemedicine", "Using statistical software"],
  "History of Medicine & Bioethics": ["Famous physicians and discoveries", "History of medicine in Africa and Zambia", "Medical oath and codes of ethics", "End-of-life ethics", "Reproductive ethics", "Resource allocation and justice", "Medical law in Zambia"],
  "Neuroscience": ["Ion channels and the action potential", "Neurotransmitters and receptors", "Spinal cord and reflexes", "Somatosensory and pain pathways", "Vision and hearing pathways", "Basal ganglia and cerebellum", "Autonomic nervous system", "Hypothalamus and limbic system", "Cerebral cortex, language and memory", "Neural development and plasticity", "Cerebrospinal fluid and blood supply of the brain"],
  "English for Medical Purposes": ["Grammar for medical writing", "Case presentation and ward-round language", "Writing referral letters and discharge summaries", "Listening and note-taking in lectures", "Medical abbreviations and Latin terms in English", "Academic writing and referencing"],

  "Pathology": ["General pathology: cell adaptation and injury", "Haemodynamic disorders: thrombosis, embolism, infarction", "Inflammation and tissue repair", "Immunopathology and amyloidosis", "Genetic and paediatric diseases", "Infectious disease pathology", "Tumours: grading, staging and spread", "Endocrine pathology", "Nervous system pathology", "Bone and joint pathology", "Skin and breast pathology", "Female and male genital tract pathology", "Nutritional and environmental pathology", "Lymphoid and haematopoietic tumours"],
  "Pharmacology": ["Pharmacokinetics (absorption, distribution, metabolism, excretion)", "Pharmacodynamics: receptors and dose-response", "Adverse drug reactions and drug interactions", "Cholinergic drugs", "Adrenergic drugs", "Antihypertensives and diuretics", "Antianginal, antiarrhythmic and heart failure drugs", "Lipid-lowering drugs", "Antibiotics: cell wall, protein synthesis and DNA inhibitors", "Antituberculosis and antileprotic drugs", "Antifungal and antiviral drugs (including antiretrovirals)", "Antimalarial and antiparasitic drugs", "Sedatives, hypnotics and anxiolytics", "Antiepileptic and antiparkinsonian drugs", "Antipsychotic, antidepressant and mood-stabilising drugs", "Opioids and NSAIDs", "General and local anaesthetics", "Antidiabetic drugs and insulin", "Thyroid and corticosteroid drugs", "Sex hormones and contraceptives", "Drugs for asthma and cough", "Drugs for peptic ulcer, nausea and diarrhoea", "Anticoagulants, antiplatelets and thrombolytics", "Drugs used in anaemia", "Drugs in pregnancy and in children", "Prescription writing"],
  "Microbiology & Parasitology": ["General bacteriology: structure, growth and genetics", "Sterilisation and disinfection", "Gram-positive cocci (Staphylococcus, Streptococcus)", "Gram-negative bacteria (Enterobacteriaceae, Neisseria, Vibrio)", "Mycobacteria and Clostridia", "Spirochaetes, Chlamydia and Rickettsia", "RNA viruses (including HIV, influenza, hepatitis)", "DNA viruses (herpes, hepatitis B, HPV)", "Pathogenic fungi", "Protozoa (Plasmodium, Trypanosoma, Entamoeba)", "Helminths: nematodes, cestodes, trematodes", "Antimicrobial resistance", "Laboratory diagnosis of infections", "Normal flora and hospital infections"],
  "Immunology": ["Cells and organs of the immune system", "Antigens and antibodies", "Complement and cytokines", "MHC and antigen presentation", "T-cell and B-cell responses", "Immune tolerance and transplantation", "Tumour immunology", "Vaccines and immunisation schedules", "Immunological laboratory tests"],
  "Community Health & Epidemiology": ["Measures of disease frequency", "Study designs: cohort, case-control, trials", "Screening and diagnostic tests", "Epidemiology of communicable diseases in Zambia", "Non-communicable diseases and risk factors", "Immunisation programmes and surveillance", "Maternal and child health", "Environmental and occupational health", "Health promotion and education", "Outbreak investigation"],
  "Pathological Anatomy": ["Pathology of the heart and blood vessels", "Pathology of the lungs and pleura", "Pathology of the stomach and intestines", "Pathology of the liver and pancreas", "Pathology of the kidney and urinary tract", "Pathology of the nervous system", "Pathology of the endocrine system", "Pathology of the female genital tract and breast", "Pathology of bone and soft tissue", "Infectious diseases: tuberculosis, HIV and others", "Haematological and lymphoid pathology", "Autopsy practice and cause of death"],
  "Pathological Physiology": ["Disorders of the cardiovascular system", "Disorders of the respiratory system", "Disorders of the digestive system and liver", "Disorders of the kidney", "Endocrine disorders", "Disorders of the nervous system and pain", "Disorders of blood and haemostasis", "Immunological disorders and allergy", "Starvation, obesity and metabolic syndrome", "Stress, adaptation and ageing"],
  "Operative Surgery & Topographic Anatomy": ["Topographic anatomy of the upper and lower limbs", "Topography of the thorax and mediastinum", "Topography of the abdomen and pelvis", "Surgical anatomy of hernias", "Surgical anatomy of the vessels and nerves", "Tracheostomy and chest drain", "Amputations and fasciotomy", "Laparotomy and intestinal anastomosis", "Wound management and closure"],
  "Hygiene & Ecology": ["Air hygiene and microclimate", "Water supply and sanitation", "Soil and waste disposal", "Food hygiene and foodborne diseases", "Nutrition standards and malnutrition", "Hygiene of children and adolescents", "Radiation hygiene", "Hygiene of hospitals and health facilities", "Occupational hygiene and toxic exposures", "Climate and health"],
  "Clinical Immunology & Allergy": ["Primary immunodeficiencies", "Secondary immunodeficiency and HIV", "Allergic rhinitis, asthma and anaphylaxis", "Drug and food allergy", "Autoimmune diseases: diagnosis and treatment", "Immunosuppressive and biological therapy", "Immunodiagnostics: skin tests and serology"],
  "Basic Radiology & Imaging": ["Chest X-ray: normal and common abnormalities", "Abdominal X-ray and contrast studies", "Skeletal radiology and fractures", "Ultrasound in obstetrics and the abdomen", "CT of the head and body", "MRI basics and indications", "Nuclear medicine and PET", "Interventional radiology"],
  "Propaedeutics of Internal Diseases": ["General examination", "Examination of the heart and heart murmurs", "Examination of the lungs and chest signs", "Examination of the abdomen, liver and spleen", "Examination of the kidneys and urinary system", "Examination of the blood system and lymph nodes", "Examination of the endocrine system", "Examination of the locomotor system", "Neurological examination", "Writing the case history"],

  "Internal Medicine": ["Rheumatology", "Neurology", "Geriatric medicine", "Acute medicine and emergencies", "Diabetes and metabolic disease", "Poisoning and toxicology", "Oncology basics", "Dermatology in medicine", "HIV medicine and opportunistic infections", "Tropical medicine"],
  "General Surgery": ["Surgical infections and wound healing", "Burns", "Hernias", "Oesophagus, stomach and duodenum surgery", "Small and large bowel surgery", "Hepatobiliary and pancreatic surgery", "Vascular surgery", "Thyroid and parathyroid surgery", "Anaesthesia and perioperative care", "Surgical oncology", "Paediatric surgery basics", "Orthopaedic and plastic surgery basics"],
  "Clinical Skills": ["Blood pressure and vital signs", "Venepuncture and cannulation", "Urinary catheterisation", "Suturing and wound care", "Basic and advanced life support", "ECG recording", "Lumbar puncture and chest drain", "Airway and oxygen therapy", "Breaking bad news and consent", "Prescribing and writing orders"],
  "Behavioural Science": ["Stress, coping and illness behaviour", "Doctor-patient relationship", "Learning, memory and motivation", "Personality and development across the life span", "Health beliefs and culture in Zambia", "Death, dying and grief", "Substance use and addiction", "Sexuality and gender"],
  "Clinical Pharmacology": ["Pharmacokinetics in disease (renal and hepatic failure)", "Pharmacogenetics", "Clinical trials and drug development", "Drugs in pregnancy and breastfeeding", "Drugs in children and the elderly", "Drug dosing and calculations", "Drug poisoning and antidotes", "Essential Medicines List and Zambian Standard Treatment Guidelines", "Pharmacovigilance and drug regulation"],
  "Cardiology": ["Heart failure drugs and devices", "Acute coronary syndrome", "Atrial fibrillation and other arrhythmias", "Infective endocarditis", "Rheumatic heart disease", "Congenital heart disease in adults", "Pericardial disease", "Syncope and sudden cardiac death", "Peripheral arterial disease", "Echocardiography and stress testing"],
  "Pulmonology": ["Tuberculosis of the lung", "Respiratory failure and oxygen therapy", "Bronchiectasis and cystic fibrosis", "Pleural effusion and pneumothorax", "Sleep apnoea", "Occupational lung disease", "Lung function tests and blood gases", "Respiratory infections in HIV"],
  "Gastroenterology & Hepatology": ["Gastro-oesophageal reflux and peptic ulcer", "Diarrhoea and malabsorption", "Coeliac disease", "Viral hepatitis", "Alcohol and drug-induced liver disease", "Complications of cirrhosis", "Gallstones and cholecystitis", "Colorectal cancer and screening", "Endoscopy and liver function tests"],
  "Nephrology": ["Nephrotic and nephritic syndromes", "Urinary tract infection", "Hypertension and the kidney", "Diabetic kidney disease", "Renal replacement therapy", "Kidney stones", "Kidney disease in HIV", "Renal drug dosing"],
  "Haematology": ["Iron deficiency and other anaemias", "Haemolytic anaemias and G6PD deficiency", "Thalassaemia", "Acute and chronic leukaemias", "Lymphoma and myeloma", "Haemophilia and von Willebrand disease", "Venous thromboembolism and anticoagulation", "Bone marrow failure and transplantation", "Blood transfusion reactions", "Blood film and laboratory interpretation"],
  "Rheumatology": ["Osteoarthritis", "Systemic sclerosis and myositis", "Juvenile idiopathic arthritis", "Osteoporosis", "Back pain", "Septic arthritis", "Rheumatic fever", "Disease-modifying and biological drugs"],
  "Nutrition & Dietetics": ["Carbohydrates, fats and proteins in the diet", "Vitamins and minerals in the diet", "Nutrition in pregnancy and infancy", "Severe acute malnutrition: kwashiorkor and marasmus", "Diet in diabetes, hypertension and renal disease", "Nutritional assessment", "Food security and nutrition programmes in Zambia", "Eating disorders"],

  "Obstetrics & Gynaecology": ["Physiology of pregnancy and fetal development", "Normal labour and the partograph", "Antepartum haemorrhage", "Postpartum haemorrhage", "Hypertensive disorders of pregnancy and eclampsia", "Diabetes and infections in pregnancy", "Prevention of mother-to-child transmission of HIV", "Caesarean section and instrumental delivery", "Abortion and ectopic pregnancy", "Menstrual disorders and amenorrhoea", "Infertility", "Menopause", "Cervical cancer screening and gynaecological cancers", "Fibroids, endometriosis and ovarian cysts", "Contraception", "Postnatal care"],
  "Paediatrics": ["Newborn care and neonatal resuscitation", "Neonatal jaundice and sepsis", "Prematurity and low birth weight", "Respiratory infections in children", "Diarrhoea and dehydration", "Malaria in children", "Severe acute malnutrition", "Paediatric HIV", "Congenital heart disease", "Convulsions and meningitis", "Anaemia and sickle cell disease in children", "Immunisation schedule", "Childhood nephrology and cardiology", "Integrated Management of Childhood Illness", "Child abuse and developmental disorders", "Genetic and chromosomal disorders in children"],
  "Psychiatry": ["Psychiatric history and mental state examination", "Schizophrenia and other psychoses", "Depression and bipolar disorder", "Anxiety, OCD and PTSD", "Substance use disorders", "Dementia and delirium", "Child and adolescent psychiatry", "Suicide and self-harm", "Personality disorders", "Mental health law and Zambian services", "Antipsychotics, antidepressants and ECT"],
  "Neurology": ["Neurological examination and localisation", "Meningitis and encephalitis", "Parkinson disease and movement disorders", "Multiple sclerosis", "Peripheral neuropathy and Guillain-Barre syndrome", "Myasthenia gravis and muscle disease", "Coma and brain death", "Spinal cord disease", "Neurocysticercosis and HIV neurology", "Neuroimaging and lumbar puncture"],
  "Infectious Diseases": ["Malaria", "HIV: diagnosis and antiretroviral therapy", "Opportunistic infections in HIV", "Tuberculosis and HIV co-infection", "Cholera, typhoid and dysentery", "Meningitis and sepsis", "Hepatitis B and C", "Schistosomiasis and helminths", "Rabies, anthrax and zoonoses", "COVID-19 and emerging infections", "Immunisation and prevention", "Infection control in hospital"],
  "Endocrinology": ["Type 1 and type 2 diabetes treatment", "Diabetic emergencies (DKA and HHS)", "Diabetes complications", "Hyperthyroidism and hypothyroidism", "Goitre and thyroid cancer", "Cushing and Addison disease", "Hyperaldosteronism and phaeochromocytoma", "Acromegaly and pituitary failure", "Calcium and parathyroid disorders", "Osteoporosis and metabolic bone disease", "Disorders of growth and puberty"],
  "Geriatrics": ["Comprehensive geriatric assessment", "Pressure ulcers", "Incontinence", "Stroke and Parkinson disease in the elderly", "Osteoporosis and fractures", "Nutrition in old age", "Depression and loneliness in the elderly", "Elder abuse and legal issues"],
  "Urology": ["Benign prostatic hyperplasia", "Prostate cancer", "Bladder and kidney cancer", "Haematuria", "Urethral stricture and hypospadias", "Testicular torsion and scrotal swellings", "Erectile dysfunction and male infertility", "Urological trauma", "Schistosomiasis of the urinary tract"],
  "Dermatology & Venereology": ["Acne and rosacea", "Fungal infections of the skin", "Bacterial skin infections", "Viral skin infections and warts", "Scabies and lice", "Leprosy", "Skin signs of HIV and Kaposi sarcoma", "Drug eruptions and Stevens-Johnson syndrome", "Pigmentary disorders and albinism", "Syphilis, gonorrhoea and chlamydia", "Urticaria and angioedema", "Hair and nail disorders"],

  "Emergency Medicine": ["Triage and primary survey (ABCDE)", "Cardiac arrest and arrhythmias", "Chest pain and acute coronary syndrome", "Anaphylaxis", "Sepsis and septic shock", "Acute asthma and respiratory failure", "Burns and drowning", "Snake bite and envenomation", "Diabetic and endocrine emergencies", "Seizures and coma", "Head, chest and abdominal trauma", "Obstetric and paediatric emergencies", "Wound care and tetanus prophylaxis", "Environmental emergencies"],
  "Orthopaedics": ["Fracture healing and complications", "Upper limb fractures", "Lower limb fractures and hip fractures", "Spinal injuries and disc disease", "Osteomyelitis and septic arthritis", "Bone tumours", "Congenital deformities (clubfoot, DDH)", "Compartment syndrome", "Sports injuries and ligament tears", "Amputations and prostheses", "Plaster techniques and traction"],
  "Ophthalmology & ENT": ["Anatomy and examination of the eye", "Red eye and conjunctivitis", "Cataract", "Glaucoma", "Diabetic and hypertensive retinopathy", "Ocular trauma", "Trachoma and eye infections", "Visual acuity and refractive errors", "Ear: otitis media and hearing loss", "Nose: epistaxis, sinusitis and rhinitis", "Throat: tonsillitis, airway obstruction and head and neck cancer", "Vertigo and the vestibular system"],
  "Family Medicine & Public Health": ["Principles of primary care", "Chronic disease management in the community", "Screening and health promotion", "Community-based care and home visits", "Maternal and child health programmes", "HIV, TB and malaria programmes", "Mental health in primary care", "Referral systems and district health services"],
  "Forensic Medicine": ["Medico-legal documentation and giving evidence", "Types of injuries and wounds", "Sexual assault and child abuse", "Asphyxia, drowning and burns", "Firearm injuries", "Post-mortem changes and time of death", "Autopsy procedure", "Forensic toxicology", "Identification and DNA", "Medical negligence and ethics"],
  "Dermatology & Radiology": ["Skin lesions and morphology", "Dermatitis, psoriasis and acne", "Skin infections and infestations", "Skin cancer", "Chest and abdominal radiology", "Bone and joint radiology", "Neuroradiology", "Radiation protection"],
  "Oncology": ["Tumour biology and carcinogenesis", "Cancer staging (TNM) and grading", "Breast cancer", "Cervical and ovarian cancer", "Prostate and bladder cancer", "Lung, colorectal and gastric cancer", "Kaposi sarcoma and HIV-related cancers", "Leukaemia and lymphoma", "Childhood cancers", "Chemotherapy: drugs, toxicity and supportive care", "Radiotherapy", "Oncological emergencies", "Cancer pain and survivorship"],
  "Anaesthesiology & Intensive Care": ["Preoperative assessment and ASA grade", "General anaesthesia: induction, maintenance and reversal", "Inhalational and intravenous anaesthetic drugs", "Muscle relaxants", "Local and regional anaesthesia", "Spinal and epidural anaesthesia", "Monitoring during anaesthesia", "Postoperative care and complications", "Mechanical ventilation", "Sepsis, ARDS and organ failure", "Cardiac arrest and resuscitation", "Obstetric and paediatric anaesthesia"],
  "Phthisiology (Tuberculosis)": ["Pathogenesis and natural history of TB", "Pulmonary TB: clinical features and radiology", "Extrapulmonary TB", "TB and HIV co-infection", "TB in children", "First-line and second-line anti-TB drugs", "TB preventive therapy and BCG", "National TB control programme in Zambia", "Adverse effects of anti-TB drugs"],
  "Neurosurgery": ["Intracranial haemorrhage", "Skull fractures and brain injury grading", "Brain abscess and neurosurgical infections", "Spinal trauma", "Spinal tumours and degenerative disease", "Cerebral aneurysm and subarachnoid haemorrhage", "Congenital neural tube defects", "Neurosurgical procedures and shunts"],
  "Paediatric Surgery": ["Intussusception and pyloric stenosis", "Hirschsprung disease and anorectal malformations", "Oesophageal atresia and diaphragmatic hernia", "Abdominal wall defects", "Undescended testis and hypospadias", "Appendicitis in children", "Paediatric burns", "Paediatric oncology surgery"],
  "Cardiothoracic Surgery": ["Cardiac surgery: bypass and heart-lung machine", "Congenital heart surgery", "Thoracic aortic disease", "Empyema and lung abscess", "Lung cancer surgery", "Oesophageal surgery", "Post-operative care in cardiothoracic surgery"],
  "Palliative Care": ["Principles and the WHO analgesic ladder", "Opioids in cancer pain", "Nausea, breathlessness and other symptoms", "Spiritual and psychosocial care", "Paediatric palliative care", "Ethics and law in end-of-life care", "Palliative care in Zambia"],
  "Rehabilitation & Sports Medicine": ["Principles of rehabilitation and disability", "Physical therapy and modalities", "Rehabilitation after amputation", "Prostheses and orthoses", "Cerebral palsy and paediatric rehabilitation", "Sports injuries and prevention", "Exercise prescription", "Community-based rehabilitation"],
  "Occupational & Disaster Medicine": ["Occupational exposure and risk assessment", "Pneumoconioses and occupational asthma", "Noise, heat and vibration", "Chemical and pesticide poisoning", "Needle-stick injury and post-exposure prophylaxis", "Disaster management cycle", "Triage in disaster", "Epidemics and humanitarian emergencies"],
  "Advanced Internal Medicine": ["Endocrine and diabetes cases", "Infectious disease and HIV cases", "Haematology and oncology cases", "Neurology and psychiatry cases", "Acute medicine and critical care", "Interpretation of investigations", "Treatment decision making"],
  "Advanced Surgery": ["Trauma and polytrauma", "Hepatobiliary and pancreatic surgery", "Colorectal and anal surgery", "Breast and endocrine surgery", "Urological and gynaecological surgery cases", "Surgical audit and ethics", "ICU and surgical nutrition"],
  "Health Management & Public Health": ["Health economics and financing", "Health information systems", "Human resources and leadership", "Planning, monitoring and evaluation", "Supply chain and essential medicines", "Zambian health policy and universal health coverage", "Disaster and outbreak management", "Global health and the SDGs"],
  "ECG & Imaging Interpretation": ["Normal ECG and axis", "Arrhythmias on ECG", "Ischaemia, infarction and conduction blocks", "Chest X-ray interpretation approach", "Skeletal and abdominal X-ray", "Ultrasound findings", "CT and MRI findings of common conditions"],
  "Clinical Research Project": ["Literature review and referencing", "Ethics approval and consent", "Questionnaire design and sampling", "Data analysis and interpretation", "Writing the dissertation", "Presenting and defending research"],
  "State Exam Revision": ["Internal medicine revision", "Surgery revision", "Obstetrics and gynaecology revision", "Paediatrics revision", "Psychiatry and neurology revision", "Public health and ethics revision", "OSCE stations and practice"],
};
for (const l of Object.values(STARTER)) for (const c of l) {
  const have = new Set(c.topics.map((t) => t.toLowerCase()));
  c.topics = [...c.topics, ...(MORE[c.title] || []).filter((t) => !have.has(t.toLowerCase()))];
}

// Deterministic ids, so seeding twice (or on two servers at once) can never create duplicates.
const cid = (y, t) => crypto.createHash("sha1").update(y + ":" + t).digest("hex").slice(0, 12);
export const courseId = cid;
export const seedCourses = () =>
  Object.entries(STARTER).flatMap(([y, l]) => l.map((c) => ({ id: cid(y, c.title), year: +y, title: c.title, topics: c.topics })));

// Study-reference starter rows. Written from general textbook knowledge, NOT a verified formulary.
// No doses on purpose. Check against your own textbook / lab / national guidelines, then edit freely.
const D = (name, cls, use, adverse, notes) => ({ name, cls, use, adverse, notes });
const L = (test, range, notes = "") => ({ test, range, notes });

export const seedRefs = () => {
  const withIds = (a) => a.map((r) => ({ id: crypto.randomBytes(6).toString("hex"), ...r }));
  return {
    drugs: withIds([
      D("Metformin", "Biguanide", "Lowers hepatic glucose output, improves insulin sensitivity. First-line type 2 diabetes.", "GI upset, B12 deficiency (long term), lactic acidosis (rare)", "Avoid in severe renal impairment; hold during acute illness and around iodinated contrast."),
      D("Lisinopril", "ACE inhibitor", "Blocks angiotensin II formation. Hypertension, heart failure, diabetic kidney disease.", "Dry cough, hyperkalaemia, angioedema, first-dose hypotension", "Contraindicated in pregnancy. Check creatinine and potassium."),
      D("Losartan", "ARB (AT1 blocker)", "Blocks angiotensin II at the AT1 receptor. Alternative when ACE inhibitor cough occurs.", "Hyperkalaemia, hypotension, dizziness", "Contraindicated in pregnancy. Do not combine casually with ACE inhibitors."),
      D("Amlodipine", "Dihydropyridine calcium channel blocker", "Vasodilation via L-type Ca channel block. Hypertension, angina.", "Ankle oedema, flushing, headache", "Oedema is not helped by diuretics as much as expected (it is vasodilatory)."),
      D("Atenolol", "Beta-1 selective blocker", "Lowers heart rate, contractility, renin. Hypertension, angina, post-MI, AF rate control.", "Bradycardia, fatigue, cold extremities, bronchospasm, can mask hypoglycaemia", "Do not stop abruptly. Caution in asthma/COPD and heart block."),
      D("Furosemide", "Loop diuretic", "Blocks Na-K-2Cl cotransporter in the thick ascending limb. Oedema, heart failure.", "Hypokalaemia, hyponatraemia, dehydration, ototoxicity, hyperuricaemia", "Monitor electrolytes and renal function."),
      D("Hydrochlorothiazide", "Thiazide diuretic", "Blocks Na-Cl cotransporter in the distal tubule. Hypertension.", "Hypokalaemia, hyponatraemia, hypercalcaemia, hyperglycaemia, hyperuricaemia (gout)", "Thiazides reduce urinary calcium loss."),
      D("Spironolactone", "Aldosterone antagonist (K-sparing)", "Blocks aldosterone receptor. Heart failure, ascites, hyperaldosteronism.", "Hyperkalaemia, gynaecomastia", "Watch potassium, especially with ACE inhibitors / ARBs."),
      D("Atorvastatin", "Statin (HMG-CoA reductase inhibitor)", "Lowers LDL cholesterol; cardiovascular prevention.", "Myalgia, myopathy/rhabdomyolysis (rare), raised liver enzymes", "Avoid in pregnancy. Interacts with some macrolides and azole antifungals (CYP3A4)."),
      D("Aspirin (low dose)", "Antiplatelet (COX inhibitor)", "Irreversibly blocks platelet thromboxane A2 production.", "GI irritation/bleeding, bronchospasm in sensitive asthmatics, tinnitus at high doses", "Avoid in children with viral illness (Reye syndrome)."),
      D("Warfarin", "Vitamin K antagonist", "Blocks vitamin K epoxide reductase, lowering factors II, VII, IX, X (and protein C/S).", "Bleeding, teratogenic, skin necrosis at start", "Monitor INR. Many drug and food interactions. Reversal: vitamin K, prothrombin complex concentrate."),
      D("Amoxicillin", "Aminopenicillin (beta-lactam)", "Blocks bacterial cell wall synthesis (penicillin-binding proteins).", "Diarrhoea, rash, hypersensitivity/anaphylaxis", "Check penicillin allergy. Rash is common if given during infectious mononucleosis."),
      D("Gentamicin", "Aminoglycoside", "Binds 30S ribosome; bactericidal against many Gram-negatives.", "Nephrotoxicity, ototoxicity, neuromuscular blockade", "Narrow safety margin: monitor levels and renal function; avoid with other nephrotoxins."),
      D("Ciprofloxacin", "Fluoroquinolone", "Inhibits DNA gyrase / topoisomerase IV.", "Tendinopathy/rupture, QT prolongation, CNS effects, C. difficile", "Absorption reduced by calcium, iron, magnesium, aluminium. Generally avoided in children."),
      D("Rifampicin", "Antimycobacterial (RNA polymerase inhibitor)", "Tuberculosis, leprosy; part of standard TB regimens.", "Orange body fluids, hepatotoxicity, flu-like syndrome", "Strong enzyme inducer: lowers levels of many drugs (hormonal contraception, warfarin, some antiretrovirals)."),
      D("Isoniazid", "Antimycobacterial", "Inhibits mycolic acid synthesis. Tuberculosis.", "Peripheral neuropathy, hepatotoxicity, drug-induced lupus", "Give pyridoxine (B6) to prevent neuropathy. Acetylator status varies."),
      D("Artemether-lumefantrine", "Artemisinin combination therapy", "Treatment of uncomplicated P. falciparum malaria.", "Headache, dizziness, nausea, QT prolongation", "Take with fatty food for lumefantrine absorption. Follow your national malaria guideline."),
      D("Omeprazole", "Proton pump inhibitor", "Irreversibly blocks gastric H+/K+ ATPase. Reflux, peptic ulcer.", "Headache, hypomagnesaemia, C. difficile risk, reduced B12/iron absorption long term", "Reassess long-term use."),
      D("Salbutamol", "Short-acting beta-2 agonist", "Bronchodilator for asthma/COPD relief.", "Tremor, tachycardia, hypokalaemia", "Overuse signals poorly controlled asthma."),
      D("Prednisolone", "Glucocorticoid", "Anti-inflammatory and immunosuppressive.", "Hyperglycaemia, osteoporosis, adrenal suppression, mood change, infection risk, peptic ulcer", "Do not stop abruptly after prolonged use."),
      D("Paracetamol", "Analgesic / antipyretic", "Pain and fever.", "Hepatotoxicity in overdose", "Overdose antidote: N-acetylcysteine. Respect maximum daily limits."),
      D("Ibuprofen", "NSAID (non-selective COX inhibitor)", "Pain, inflammation, fever.", "GI ulcer/bleeding, acute kidney injury, fluid retention, bronchospasm in sensitive asthmatics", "Avoid in late pregnancy. ACE inhibitor + diuretic + NSAID is a classic kidney-injury combination."),
      D("Morphine", "Opioid (mu agonist)", "Severe pain.", "Respiratory depression, constipation, nausea, sedation, dependence", "Naloxone reverses. Metabolites accumulate in renal impairment."),
      D("Digoxin", "Cardiac glycoside", "Inhibits Na+/K+ ATPase. AF rate control, heart failure.", "Nausea, visual disturbance (yellow-green), arrhythmias", "Narrow therapeutic index. Hypokalaemia increases toxicity."),
    ]),
    labs: withIds([
      L("Sodium", "135-145 mmol/L"),
      L("Potassium", "3.5-5.0 mmol/L", "Haemolysed samples read falsely high."),
      L("Chloride", "98-106 mmol/L"),
      L("Bicarbonate", "22-28 mmol/L"),
      L("Urea", "2.5-7.1 mmol/L (BUN about 7-20 mg/dL)"),
      L("Creatinine", "Male about 60-110, female about 45-90 umol/L (about 0.7-1.2 / 0.5-1.0 mg/dL)", "Depends on muscle mass, age and sex."),
      L("eGFR", ">=90 normal (G1); 60-89 (G2); 45-59 (G3a); 30-44 (G3b); 15-29 (G4); <15 (G5) mL/min/1.73m2", "Staging needs persistence over 3 months plus markers of damage for G1-G2."),
      L("Glucose, fasting", "3.9-5.5 mmol/L (70-99 mg/dL)", "Diabetes: fasting 7.0 mmol/L (126 mg/dL) or more, confirmed."),
      L("HbA1c", "Below 5.7% normal; 5.7-6.4% prediabetes; 6.5% (48 mmol/mol) or more diabetes", "These are the ADA cut-offs; some guidelines (e.g. UK, WHO) define prediabetes differently. Unreliable in anaemia and haemoglobinopathies."),
      L("Calcium (total)", "2.2-2.6 mmol/L (8.5-10.5 mg/dL)", "Correct for albumin."),
      L("Magnesium", "0.7-1.0 mmol/L"),
      L("Phosphate", "0.8-1.5 mmol/L"),
      L("Albumin", "35-50 g/L (3.5-5.0 g/dL)"),
      L("Bilirubin (total)", "About 3-17 umol/L (0.2-1.0 mg/dL)"),
      L("ALT", "Roughly up to 40 U/L", "Lab-dependent."),
      L("AST", "Roughly up to 40 U/L", "Lab-dependent."),
      L("ALP", "About 30-130 U/L", "Higher in children, pregnancy and bone growth."),
      L("Haemoglobin", "Male about 13.5-17.5 g/dL; female about 12.0-15.5 g/dL", "WHO anaemia cut-offs: below 13 (men), below 12 (non-pregnant women), below 11 (pregnancy)."),
      L("MCV", "80-100 fL", "Low: microcytic. High: macrocytic."),
      L("Haematocrit", "Male about 0.41-0.50; female about 0.36-0.46 L/L"),
      L("WBC", "4.0-11.0 x10^9/L"),
      L("Platelets", "150-400 x10^9/L"),
      L("Reticulocytes", "About 0.5-2.5%"),
      L("ESR", "Rule of thumb: men under age/2, women under (age+10)/2 mm/h", "Non-specific."),
      L("CRP", "Roughly under 5-10 mg/L", "Lab-dependent."),
      L("INR", "0.8-1.2 normal; on warfarin target is usually 2.0-3.0 (higher for some indications)"),
      L("aPTT", "Roughly 25-40 s", "Lab-dependent. Monitors unfractionated heparin."),
      L("Lactate", "0.5-2.0 mmol/L"),
      L("Troponin", "Assay-specific: compare with your lab's 99th percentile cut-off", "Interpret with the clinical picture and serial values."),
      L("Arterial blood gas", "pH 7.35-7.45; PaCO2 4.7-6.0 kPa (35-45 mmHg); PaO2 10-13 kPa (75-100 mmHg) on air; HCO3 22-26 mmol/L"),
      L("TSH", "About 0.4-4.0 mIU/L", "Lab-dependent."),
      L("Free T4", "About 10-22 pmol/L", "Assay-dependent."),
      L("Total cholesterol", "Desirable below 5.2 mmol/L (200 mg/dL)", "LDL targets depend on cardiovascular risk."),
      L("Triglycerides", "Below 1.7 mmol/L (150 mg/dL)", "Fasting sample."),
      L("Uric acid", "Male about 200-430, female about 140-360 umol/L"),
      L("Urine albumin:creatinine ratio", "Below 3 mg/mmol (below 30 mg/g)"),
      L("Ferritin", "About 30-400 ug/L (male), 15-150 ug/L (female)", "Acute-phase reactant: can be normal or high in inflammation despite iron deficiency."),
      L("CD4 count", "About 500-1500 cells/uL (adults)", "Follow your national HIV guidelines for treatment thresholds."),
    ]),
  };
};
